spring:
  application:
    name: finlog
  data:
    mongodb:
      uri: mongodb+srv://prajapatdipesh1203:SpringBootDipesh@cluster0.lqbor6p.mongodb.net/finlog?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /